GADS.o: GADS.java GADS_Interface.java
	javac GADS.java
GADS_Interface.o: GADS_Interface.java
	javac GADS_Interface.java
run:
	./test_script
runuserentry:
	./run_in_user_input_mode
clean:
	rm GADS.class
	rm GADS_Interface.class
